package com.lhsystems.prototype.pricingancillary.datagenerator;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Class that randomly generates Flights
 *
 * @author Janek Reichardt
 * @version $Revision: 1.10 $
 */
final public class FlightGenerator {

    /**
     * Generates a stream of pseudorandom numbers used for generating flights.
     */
    private final Random random = new Random();

    /**
     * Counter to remember which numbers have been used as <code>id</code>
     * already.
     */
    private long idCounter;

    /**
     * Counter to remember which numbers have been used as
     * <code>flightNumber</code> already.
     */
    private int flightNumberCounter;

    /**
     * Static HashMap of airports and their corresponding <code>Market</code> to
     * be used for the generation of flights.
     */
    private static final List<Airport> AIRPORTS = new ArrayList<Airport>() {
        /**
         * Identifier for <code>AIRPORTS</code>.
         */
        private static final long serialVersionUID = 1L;

        {
            add(new Airport("FRA", "Frankfurt Airport", Market.DOMESTIC));
            add(new Airport("TXL", "Berlin Tegel Airport", Market.DOMESTIC));
            add(new Airport("OSL", "Oslo Gardermoen", Market.CONTINENTAL));
            add(new Airport("BCN", "Barcelona El Prat", Market.CONTINENTAL));
            add(new Airport("LGW", "London Gatwick", Market.CONTINENTAL));
            add(
                    new Airport(
                            "EZE",
                            "Buenos Aires Ezeiza",
                            Market.INTERCONTINENTAL));
            add(
                    new Airport(
                            "TFS",
                            "Tenerife South Airport",
                            Market.INTERCONTINENTAL));

        }
    };

    /**
     * Constructor.
     *
     * @param startId
     *            a lower bound for the numbers used to compute the Ids of
     *            flights
     *
     */
    public FlightGenerator(final Long startId) {
        /**
         * Here one could set additional generation options as attributes of the
         * generator
         */
        setIdCounter(startId);
    }

    /**
     * This method generates a number of flights randomly and returns them in an
     * ArrayList. The flights are generated randomly according to
     * {@link FlightGenerator#generateFlight() 'generateFlight'}. In particular
     * the identifiers 'id' are selected such that they are unique for all
     * flights generated by this instance. The departure time and date are
     * chosen randomly. Origin and destination are chosen randomly from the keys
     * of the predefined ArrayList <code>AIRPORTS</code>. The larger one of the
     * corresponding <code>Markets</code> is chosen for the flight.
     *
     * @param numberOfFlights
     *            the number of flights to be generated
     * @return an ArrayList of flights
     */
    public List<Flight> generateFlights(final int numberOfFlights) {
        return Stream.iterate(0, n -> n + 1).limit(numberOfFlights).map(
                n -> generateFlight()).collect(Collectors.toList());
    }

    /**
     * Returns the constant HashMap <code>AIRPORTS</code>.
     *
     * @return the constant HashMap <code>AIRPORTS</code>
     */
    private static List<Airport> getAirports() {
        return AIRPORTS;
    }

    /**
     * {@see generateFlights()} for more details.
     *
     * @return a randomly generated flight
     */
    private Flight generateFlight() {
        final long id = increaseIdCounter();
        final int flightNumber = increaseFlightNumberCounter();
        // returns a Random Day of 2018 or 2019
        final LocalDate departureDate = getRandomDay(17532, 730);
        final LocalTime departureTime = getRandomDaytime();
        final Airport originAirport = getRandomAirport();
        final Airport destinationAirport = getDestinationAirport(originAirport);
        final Market market = originAirport.getMarket().getMaximumMarket(
                destinationAirport.getMarket());
        return new Flight(
                id,
                flightNumber,
                departureTime,
                departureDate,
                originAirport.getIata(),
                destinationAirport.getIata(),
                market);
    }

    /**
     * Returns a random <code>Airport</code> which is different from
     * <code>originAirport</code>.
     *
     * @param originAirport
     *            some <code>Airport</code>
     * @return destinationAirport which is different from originAirport
     */
    private Airport getDestinationAirport(final Airport originAirport) {
        Airport destinationAirport = getRandomAirport();
        while (originAirport == destinationAirport) {
            destinationAirport = getRandomAirport();
        }
        return destinationAirport;
    }

    /**
     * Returns the random number generator of this object.
     *
     * @return this.random
     */
    private Random getRandom() {
        return random;
    }

    /**
     * Returns a randomly chosen <code>Airport</code> out of
     * <code>AIRPORTS</code>.
     *
     * @return a randomly chosen <code>Airport</code> out of
     *         <code>AIRPORTS</code>
     */
    private Airport getRandomAirport() {
        return getAirports().get(getRandom().nextInt(getAirports().size()));
    }

    /**
     * Returns a randomly chosen <code>LocalDate</code> in the time interval of
     * Length <code>durationOfInterval</code> starting on
     * <code>startOfInterval</code>.
     *
     * @param startOfInterval
     *            The number of Days from 01.01.1970 to the first Day of the
     *            time interval.
     * @param durationOfInterval
     *            The number of Days from which a date is chosen.
     *
     * @return a randomly chosen <code>LocalDate</code> between
     *         <code>startOfInterval</code> and
     *         <code>startOfInterval</code>+<code>durationOfInterval</code>
     */
    private LocalDate getRandomDay(final int startOfInterval,
            final int durationOfInterval) {
        return LocalDate.ofEpochDay(
                startOfInterval + getRandom().nextInt(durationOfInterval));
    }

    /**
     * Returns a randomly generated <code>LocalTime</code>
     *
     * @return a randomly generated <code>LocalTime</code>
     */
    private LocalTime getRandomDaytime() {
        return LocalTime.of(
                getRandom().nextInt((int) TimeUnit.DAYS.toHours(1)),
                getRandom().nextInt((int) TimeUnit.HOURS.toMinutes(1)));
    }

    /**
     * Returns the <code>flightNumberCounter</code> of this object and
     * increments it.
     *
     * @return <code>this.flightNumberCounter</code>
     */
    private int increaseFlightNumberCounter() {
        final int tempHelper = flightNumberCounter;
        this.setFlightNumberCounter(flightNumberCounter + 1);
        return tempHelper;
    }

    /**
     * Returns the current value of <code>idCounter</code> and increments it.
     *
     * @return the current value of <code>idCounter</code>
     */
    private Long increaseIdCounter() {
        final Long tempHelper = idCounter;
        setIdCounter(idCounter + 1);
        return tempHelper;
    }

    /**
     * Sets the current value of <code>idCounter</code> to the given number.
     *
     * @param idCounter
     *            the number that <code>idCounter</code> is set to.
     */
    private void setIdCounter(final Long idCounter) {
        this.idCounter = idCounter;
    }

    /**
     * Sets the <code>flightNumberCounter</code> to a new number given by the
     * parameter.
     *
     * @param flightNumberCounter
     *            the number that <code>flightNumberCounter</code> is set to.
     */
    private void setFlightNumberCounter(final int flightNumberCounter) {
        this.flightNumberCounter = flightNumberCounter;
    }

}
